FROM ubuntu:26.04

ENV DEBIAN_FRONTEND=noninteractive
ENV GST_VERSION=1.28

RUN apt-get update && apt-get install -y \
    build-essential \
    git \
    pkg-config \
    python3 \
    python3-pip \
    python3-setuptools \
    python3-wheel \
    flex bison \
    # orc system (évite le sous-projet qui cherche hotdoc)
    liborc-0.4-dev \
    libglib2.0-dev \
    libssl-dev \
    libxml2-dev \
    libdrm-dev \
    libx11-dev \
    libxext-dev \
    libxv-dev \
    libasound2-dev \
    libpulse-dev \
    libvpx-dev \
    libx264-dev \
    libx265-dev \
    libaom-dev \
    libdav1d-dev \
    libde265-dev \
    wget curl \
    ca-certificates \
    && pip3 install --break-system-packages meson==1.4.0 ninja \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /opt

RUN git clone --depth=1 --branch ${GST_VERSION} \
    https://gitlab.freedesktop.org/gstreamer/gstreamer.git

WORKDIR /opt/gstreamer

RUN meson setup build \
     --prefix=/usr \
     --buildtype=release \
    -Dtests=disabled \
    -Ddoc=disabled \
    -Dintrospection=enabled \
    -Dgpl=enabled

# RUN meson setup build \
#     --prefix=/usr \
#     --buildtype=release \
#     -Dauto_features=disabled \
#     -Dorc-source=system \
#     -Ddoc=disabled \
#     -Dtests=disabled \
#     -Dexamples=disabled \
#     -Dintrospection=disabled \
#     -Dlibav=enabled \
#     -Dnls=disabled \
#     -Dtools=enabled \
#     -Dintrospection=enabled \
#     -Dgstreamer:tools=enabled \
#     -Dgst-plugins-base:tools=enabled \
#     -Dgst-plugins-base:app=enabled \
#     -Dgst-plugins-base:typefind=enabled \
#     -Dgst-plugins-base:playback=disabled \
#     -Dgst-plugins-good:isomp4=enabled \
#     -Dgst-plugins-good:rtp=enabled \
#     -Dgst-plugins-bad:mpegtsmux=enabled \
#     -Dgpl=enabled \
#     -Dgst-plugins-ugly:x264=enabled \
#     -Dlibav=disabled \
#     -Ddevtools=disabled \
#     -Dges=disabled \
#     -Dpython=disabled \
#     -Dqt5=disabled \
#     -Dqt6=disabled \
#     -Dwebrtc=disabled

RUN ninja -C build -j$(nproc)
RUN ninja -C build install
RUN ldconfig

ENV LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu
ENV GST_PLUGIN_PATH=/usr/lib/x86_64-linux-gnu/gstreamer-1.0

COPY ./test_client_gst.sh /opt/test_client_gst.sh
CMD ["gst-launch-1.0", "--version"]