# Configuration du cache sur disque
proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=video_cache:10m max_size=10g inactive=60m use_temp_path=off;

server {
    listen 80;

    # Compression pour les manifestes (M3U8 / MPD)
    gzip on;
    gzip_types application/vnd.apple.mpegurl video/f4m application/dash+xml;

    location / {
        proxy_hide_header Access-Control-Allow-Origin;
        proxy_hide_header Access-Control-Allow-Methods;
        proxy_hide_header Access-Control-Allow-Headers;

        # 2. On définit NOS headers uniques et autoritaires
        add_header 'Access-Control-Allow-Origin' '*' always;
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS' always;
        add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Icy-MetaData' always;
        add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range' always;

        # 3. Gestion du Preflight (OPTIONS)
        if ($request_method = 'OPTIONS') {
            # On ne met PAS de add_header ici, on utilise les directives globales
            add_header 'Access-Control-Max-Age' 1728000;
            add_header 'Content-Type' 'text/plain; charset=utf-8';
            add_header 'Content-Length' 0;
            return 204;
        }

        # --- Proxy Settings ---
        proxy_pass http://minio:9000;
        proxy_set_header Host $http_host; # Utilise Host:Port correct pour MinIO
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_hide_header X-Amz-Request-Id; 
        
        # --- Cache Configuration ---
        proxy_cache video_cache;
        proxy_cache_key "$scheme$proxy_host$uri";
        proxy_cache_valid 200 302 10m; 
        proxy_cache_valid 404 1m;      
        
        # --- Optimisation Streaming ---
        proxy_cache_lock on;           
        proxy_cache_use_stale error timeout updating;
        
        # Header de debug pour voir si le cache fonctionne
        add_header X-Cache-Status $upstream_cache_status;
    }

    # --- Metrics pour Prometheus ---
    location /metrics {
        stub_status on;
        access_log off;
        allow 127.0.0.1;
        allow 172.18.0.0/16; # Ajusté selon les réseaux Docker par défaut
        allow 172.16.0.0/12;
    }
}